FROM alpine:3.7

ENV GOCRON_AGENT_VERSION=v1.5.3

RUN apk add --no-cache ca-certificates  tzdata bash \
    &&  mkdir -p /app \
    &&  wget -P /tmp  https://github.com/ouqiang/gocron/releases/download/${GOCRON_AGENT_VERSION}/gocron-node-${GOCRON_AGENT_VERSION}-linux-amd64.tar.gz \
    &&  cd /tmp \
    &&  tar  zvxf gocron-node-${GOCRON_AGENT_VERSION}-linux-amd64.tar.gz  \
    &&  mv /tmp/gocron-node-linux-amd64/gocron-node /app \
    &&  rm  -rf /tmp/* \
    && echo "http://mirrors.aliyun.com/alpine/v3.6/main" > /etc/apk/repositories \
    && echo "http://mirrors.aliyun.com/alpine/v3.6/community" >> /etc/apk/repositories \
    && apk update upgrade \
    && apk add --no-cache procps unzip curl bash tzdata \
	&& apk add python3\
    && pip install requests
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone

WORKDIR /app
EXPOSE 5921

ENTRYPOINT ["/app/gocron-node", "-allow-root"]
